version: '3'

services:

  api:
    build: ./api
    container_name: pokedex-api
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=database
      - TOKEN_KEY=token_key
    networks:
      - network-pokedex-database
    ports:
      - 3000:3000
    restart: always

  database:
    container_name: pokedex-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=database
    image: mongo:6.0.5
    logging:
      driver: none
    networks:
      - network-pokedex-database
    restart: always
    volumes:
      - volume-pokedex-database-data:/data/db
      - volume-pokedex-database-config:/data/configdb

networks:
  network-pokedex-database:

volumes:
  volume-pokedex-database-data:
  volume-pokedex-database-config: