version: '3'

services:

  database:
    container_name: pokedex-database
    env_file:
      - .env
    image: mongo:6.0.5
    networks:
      - network-pokedex-database
    ports:
      - 27017:27017
    restart: always
    volumes:
      - volume-pokedex-database-data:/data/db
      - volume-pokedex-database-config:/data/configdb

networks:
  network-pokedex-database:

volumes:
  volume-pokedex-database-data:
  volume-pokedex-database-config: